pass code registry to all directive environments
ExpediaGroup/graphql-kotlin pull request #1159
Opened 2021-05-25 14:20 UTC by koenpunt

### :pencil: Description

To override datafetchers for all fields in an object using a directive, the environment should expose the `GraphQLCodeRegistry`.

Or at least the only way of overriding datafetchers from a directive on an object was by iterating over the fields and setting the datafetcher.

Something like this I expect to work:

```kt
override fun onObject(environment: KotlinSchemaDirectiveEnvironment<GraphQLObjectType>): GraphQLObjectType {
    val obj = environment.element
    val reg = environment.codeRegistry

    val expressionArgument = environment.directive.getArgument("expression")
    val expressionString = expressionArgument?.value as? String ?: return obj

    val authorizationManager = authorizationManagerForExpression(expressionString)

    obj.fieldDefinitions.forEach { field ->
        val fetcher = reg.getDataFetcher(obj, field)
        val authDataFetcher = AuthDataFetcher(fetcher, authorizationManager)
        reg.dataFetcher(obj, field, authDataFetcher)
    }

    return obj
}
```

Which I think should be possible with the provided change.

2021-05-26 19:12 UTC, dariuszkuc commented
Hello 👋 
Can you elaborate on your use case? Why would you annotate the object vs the fields? i.e. given a schema (assuming there is `@authenticated` directive)

```
type Query {
  foo: Foo @authenticated
}

type Foo {
  bar: Int!
  baz: String!
}
```

In order to retrieve `Foo` you have to execute `foo` resolver which is already marked as `@authenticated`

2021-05-27 13:42 UTC, koenpunt commented
For the use case of an `@auth` directive; if a type is used multiple times in the schema, then for every time the type is used the field should be annotated. With support for adding it to the object you don't have to;

<table>
<tr>
<td>

```graphql
type Query {
  other: OtherType
  foo: Foo @auth
}

type OtherType {
  foo: Foo @auth
}

type Foo {
  bar: Int!
  baz: String!
}
```

</td>
<td>VS</td>
<td>

```graphql
type Query {
  other: OtherType
  foo: Foo
}

type OtherType {
  foo: Foo
}

type Foo @auth {
  bar: Int!
  baz: String!
}
```

</td>
</tr>
</table>

Or if all the fields of a type require authorization, except one, you could annotate the object, and the field with the exception;

```graphql
type OtherType @auth {
  foo: Foo
  something: String
  other: OtherType @public
}
```

The latter example would probably require a less trivial implementation, but should still be doable.

The Node implementation of Apollo Server also supports a similar directive, as documented here: https://www.apollographql.com/docs/apollo-server/schema/creating-directives/#enforcing-access-permissions

And apart from authorization, this could also be used to map all fields through a specific datafetcher, for whatever purpose it might be necessary.

2021-05-28 19:16 UTC, dariuszkuc requested changes

2021-05-28 19:16 UTC, dariuszkuc commented on generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/directives/KotlinDirectiveWiringFactoryTest.kt
> +//    @Test
can you remove this commented out code

2021-05-31 09:33 UTC, koenpunt commented on generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/directives/KotlinDirectiveWiringFactoryTest.kt
> +//    @Test
Done

2021-05-31 09:33 UTC, koenpunt commented on generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/directives/KotlinDirectiveWiringFactory.kt
> +                    codeRegistry = codeRegistry ?: throw InvalidSchemaDirectiveWiringException("Unable to wire directive on an object due to a missing code registry")
Done

2021-05-31 14:11 UTC, dariuszkuc approved these changes

2021-05-31 14:12 UTC, merged

2021-05-31 17:29 UTC, dariuszkuc commented
Bump to major as it is a breaking change to hook signature.