feat: graphql-kotlin-dataloader
ExpediaGroup/graphql-kotlin pull request #1415
Opened 2022-04-12 19:59 UTC by samuelAndalon

### :pencil: Description
Extracting DataLoader into his own module - This new module will decorate the DataLoaderRegistry to have access to the each DataLoader futures

2022-04-12 20:02 UTC, dariuszkuc commented on executions/graphql-kotlin-dataloader/README.md
> +Since `graphql-java` provides [support for this pattern](https://www.graphql-java.com/documentation/v16/batching/)
should we link to the v18 instead? https://www.graphql-java.com/documentation/batching

2022-04-12 20:02 UTC, dariuszkuc commented on executions/graphql-kotlin-dataloader/README.md
> +`graphql-kotlin` provides support for `DataLoaders` with this `graphql-kotlin-dataloader` module through common interfaces
```suggestion
`graphql-kotlin` provides support for `DataLoaders` with this `graphql-kotlin-dataloader` module through common interfaces.
```

2022-04-12 20:07 UTC, dariuszkuc requested changes
Should we also update https://opensource.expediagroup.com/graphql-kotlin/docs/server/data-loaders with the info about importing this module?

2022-04-12 20:17 UTC, samuelAndalon commented
> Should we also update https://opensource.expediagroup.com/graphql-kotlin/docs/server/data-loaders with the info about importing this module?

The server would be importing it by default, not sure if its worth to add that info in the documentation

2022-04-12 21:03 UTC, dariuszkuc commented
> > Should we also update https://opensource.expediagroup.com/graphql-kotlin/docs/server/data-loaders with the info about importing this module?
> 
> The server would be importing it by default, not sure if its worth to add that info in the documentation
> 
Technically you could import it without using our server packages.

2022-04-13 03:30 UTC, dariuszkuc approved these changes

2022-04-13 03:38 UTC, merged