feat: use additional directives for schema directives
ExpediaGroup/graphql-kotlin pull request #1511
Opened 2022-08-08 19:37 UTC by samuelAndalon

### :pencil: Description
use `additionalDirectives` instead of `withSchemaDirectives`, this method should be marked as depreacted, will open a PR in graphql-java

### :link: Related Issues
https://github.com/ExpediaGroup/graphql-kotlin/issues/1510

2022-08-08 20:08 UTC, dariuszkuc requested changes
Can we add a test to verify the behavior?

2022-08-09 14:35 UTC, dariuszkuc approved these changes

2022-08-09 14:45 UTC, tapaderster commented
is it because we are not adding the `Contact` directive here:
https://github.com/ExpediaGroup/graphql-kotlin/blob/master/generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaGeneratorHooks.kt#L92

2022-08-09 14:50 UTC, dariuszkuc commented
@tapaderster no, its because of broken logic in `graphql-java` that does not add the schema directives to the schema, we changed logic to explicitly add those to "additional" directives as a workaround.

2022-08-09 16:15 UTC, merged