Issue 1566
ExpediaGroup/graphql-kotlin pull request #1571
Opened 2022-10-05 21:54 UTC by hchen

### :pencil: Description
Relax federated type validation rules
- allow base type to have fields with `@external` directive
- allow base type to have fields with `@requires` directive
- allow base type to have fields with `@requires` directive referring to fields with `@external` directive

### :link: Related Issues

#1566

2022-10-11 19:42 UTC, dariuszkuc commented on generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/validation/integration/FederatedKeyDirectiveIT.kt
> +    @Disabled("This is a valid case according to Federation 2 spec")
instead of disabling this test, this code (and referenced sample project) should be deleted

2022-10-11 19:42 UTC, dariuszkuc commented on generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/validation/integration/FederatedRequiresDirectiveIT.kt
> +    @Disabled("this is a valid use case according to Federation 2 spec")
instead of disabling this test, this code (and referenced sample project) should be deleted

2022-10-11 19:47 UTC, dariuszkuc commented on generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/validation/validateRequiresDirective.kt
> +        return validateDirective("$validatedType.${validatedField.name}", REQUIRES_DIRECTIVE_NAME, validatedField.allAppliedDirectivesByName, fieldMap, extendedType)
this validation should be applied for both base and extended type -> it doesn't make sense to keep this file anymore, move this `validateDirective` call directly to [`FederatedSchemaValidator`](https://github.com/ExpediaGroup/graphql-kotlin/blob/82ae4bb4de0d26658dc16ed950a9d4f91362b788/generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/validation/FederatedSchemaValidator.kt#L71)

2022-10-11 19:48 UTC, dariuszkuc commented on generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/validation/FederatedSchemaValidatorTest.kt
> +    fun `validate local GraphQLObjectType with valid key directive and field with external directive`() {
lets just drop this test

2022-10-11 19:50 UTC, dariuszkuc commented on generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/validation/ValidateRequiresDirectiveKtTest.kt
> +    fun `Verify non extended types and non requires fields returns no error`() {
i think those tests should be dropped

2022-10-11 19:51 UTC, dariuszkuc requested changes
see comments

2022-10-12 18:58 UTC, dariuszkuc approved these changes

2022-10-12 19:26 UTC, hchen commented
retest

2022-10-12 20:06 UTC, merged