Rename federation to federated
ExpediaGroup/graphql-kotlin pull request #963
Opened 2020-12-08 22:46 UTC by smyrick

### :pencil: Description
Rename the classes before we published from `Federation*` to `Federated*` to match patterns of other classes. We have not published yet so it is not a breaking change.

### :link: Related Issues

2020-12-08 22:49 UTC, dariuszkuc requested changes
Need to update https://github.com/ExpediaGroup/graphql-kotlin/blob/3.x.x/docs/spring-server/spring-graphql-context.md

2020-12-08 23:09 UTC, dariuszkuc approved these changes

2020-12-08 23:24 UTC, dariuszkuc commented on graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/FederatedSchemaAutoConfiguration.kt
> +    @ConditionalOnProperty(value = ["graphql.federation.tracing.enabled"], havingValue = "true")
should we add `match if missing` as well?

2020-12-09 00:50 UTC, smyrick commented
You can now see tracing locally if you pass in the federation headers:

![Uploading Screen Shot 2020-12-08 at 4.37.18 PM.png…]()

2020-12-09 01:40 UTC, smyrick commented
This one is ready to go now, the 4.x.x changes here are blocked by the graphql-java 16 update: https://github.com/ExpediaGroup/graphql-kotlin/pull/962

2020-12-09 02:53 UTC, dariuszkuc requested changes
can you update https://github.com/ExpediaGroup/graphql-kotlin/blob/3.x.x/docs/spring-server/spring-beans.md and https://github.com/ExpediaGroup/graphql-kotlin/blob/3.x.x/docs/spring-server/spring-properties.md as well?

2020-12-09 02:55 UTC, dariuszkuc commented
I think we should also add a blurb about the federated context to https://github.com/ExpediaGroup/graphql-kotlin/blob/3.x.x/docs/spring-server/spring-graphql-context.md (as currently that info is under federated tracing info which may not be obvious)

2020-12-09 03:26 UTC, dariuszkuc approved these changes

2020-12-09 04:23 UTC, merged